### PR TITLE
use sans-serif font most of the time

### LINKED ISSUE #84: HTML generated from the plugin has been changed to use monospaced fonts for explanatory text
This is important because in specification documents, non-technical people expect to see proportional fonts in explanatory material.

### 👓 What did you see?

Fixed fonts in the generated HTML from the html plugin for the explanatory text for features, rules, and scenarios, i.e., the text generated by markdown. The relevant part of the generated HTML seems to be 

  `.cucumber-theme--dark{ ... }.cucumber{font-size:14px;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;color:var(--cucumber-text-color, cucumber/cucumber-jvm#222);background:var(--cucumber-background-color, white)}.cucumber pre{font-family:inherit} ...`

### ✅ What did you expect to see?

Formally proportional fonts were used. I was using Cucumber 6.10.2.

### 📦 Which version are you using?

I have just upgraded to Cucumber 7.2.3, where I had the problem. I use Java 17 with Gradle 7.4 on a Windows 10 machine. I typically run from Eclipse using Buildship.

### 🤔 Anything else?

As a workaround, I added the Georgia font and the serif family at the beginning of the list of font-families. I am not a font expert and make no claim that Georgia is what Cucumber should use.

`.cucumber{font-size:14px;font-family:Georgia,serif,ui-monospace, ...`

and then I changed the preformated from inherit to the list of monospaced font-families:

`.cucumber pre{font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace}`

### PR DESCRIPTION
**Pull request by davidjgoss**
### 🤔 What's changed?

Changed the font for our React components to sans serif (copied from [Tailwind's standard sans-serif stack](https://tailwindcss.com/docs/font-family)) except:

- Error messages (and stack traces)
- Doc strings
- Text attachments

### ⚡️ What's your motivation? 

Fixes #84.

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by davidjgoss** [comment]
@aurelien-reeves this took me a while to figure out!

Here's the feature from the CCK:

```gherkin
Feature: Attachments
  It is sometimes useful to take a screenshot while a scenario runs.
  Or capture some logs.

  Cucumber lets you `attach` arbitrary files during execution, and you can
  specify a content type for the contents.

  Formatters can then render these attachments in reports.

  Attachments must have a body and a content type

  Scenario: Strings can be attached with a media type
    Beware that some formatters such as @cucumber/react use the media type
    to determine how to display an attachment.

    When the string "hello" is attached as "application/octet-stream"
```

From debugging, it seems the leading whitespace in the descriptions is preserved when Gherkin parses, so each line of the scenario description has four leading spaces. We then treat it as Markdown, which interprets the four leading spaces as a code block:

image

Is this something we need to fix in Gherkin i.e. replicate the same behaviour as doc strings for normalising indentation?

**Comment by aurelien-reeves** [comment]
Wow 🤯

I would say that we may have to fix this in gherkin. I see any reason why those spaces are kept in the description.

However, @aslakhellesoy may certainly have way more context than I have 😅

**Comment by aurelien-reeves** [comment]
In the meantime, we may consider that PR done and treat that "issue" apart, whatever we decide it is an issue in gherkin, or we should treat it in react

**Review by aurelien-reeves — APPROVED** [review]

**Comment by mattwynne** [comment]
Agree we should fix this in Gherkin.

**Pull request merged**
